### ISSUE TITLE
Taffy is corrupting Ogg/Vorbis files

### ISSUE THREAD

**Issue by nguillaumin** [jangler/taffy#5] opened 2018-03-25 00:48 UTC
Hi,

Taffy seems to be corrupting Ogg/Vorbis files when applying tags.

Consider the following, valid Ogg/Vorbis file:

```
$ ogginfo 01\ -\ Je\ t\'ai\ manqué.ogg

Processing file "01 - Je t'ai manqué.ogg"...

New logical stream (#1, serial: 2a848e12): type vorbis
Vorbis headers parsed for stream 1, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20150105 (⛄⛄⛄⛄)
Channels: 2
Rate: 44100

Nominal bitrate: 192.000000 kb/s
Upper bitrate not set
Lower bitrate not set
User comments section follows...
	CDDB=
	ACOUSTID_FINGERPRINT=
	ACOUSTID_ID=
	ALBUM=Bleu pétrole
	ALBUM ARTIST=Alain Bashung
	ALBUMARTIST=Alain Bashung
	ALBUMARTIST_CREDIT=Alain Bashung
	ALBUMARTISTSORT=Bashung, Alain
	MUSICBRAINZ_ALBUMCOMMENT=
	MUSICBRAINZ_ALBUMSTATUS=Official
	MUSICBRAINZ_ALBUMTYPE=album
	ARRANGER=
	ARTIST=Alain Bashung
	ARTIST_CREDIT=Alain Bashung
	ARTISTSORT=Bashung, Alain
	ASIN=B0013D2X6C
	BPM=0
	CATALOGNUMBER=530 592 9
	COMPILATION=0
	COMPOSER=Gaëtan Roussel
	RELEASECOUNTRY=FR
	DATE=2008-03-24
	YEAR=2008
	DISC=1
	DISCNUMBER=1
	DISCSUBTITLE=
	DISCTOTAL=1
	DISCC=1
	TOTALDISCS=1
	ENCODEDBY=
	ENCODER=
	GENRE=
	GROUPING=
	LABEL=Barclay
	PUBLISHER=Barclay
	LANGUAGE=fra
	LYRICIST=Gaëtan Roussel
	LYRICS=
	MUSICBRAINZ_ALBUMARTISTID=d31e78a3-4fd8-4b10-9c49-0ee8d4dfd61e
	MUSICBRAINZ_ALBUMID=2a8233d9-dd22-4f0c-a3c6-b79c4d521c72
	MUSICBRAINZ_ARTISTID=d31e78a3-4fd8-4b10-9c49-0ee8d4dfd61e
	MUSICBRAINZ_RELEASEGROUPID=6a0fb53e-bbea-35de-99ed-6dc94373c549
	MUSICBRAINZ_TRACKID=d48bdec8-1e79-4ae8-ba69-58354ed0ed62
	MEDIA=CD
	ORIGINALDATE=2008-03-24
	SCRIPT=Latn
	TITLE=Je t'ai manqué
	TRACK=1
	TRACKNUMBER=1
	TRACKTOTAL=11
	TRACKC=11
	TOTALTRACKS=11
Vorbis stream 1:
	Total data length: 5304314 bytes
	Playback length: 3m:41.733s
	Average bitrate: 191.376332 kb/s
Logical stream 1 ended
```

Using Taffy to set the Genre tag: `taffy -g Chanson 01\ -\ Je\ t\'ai\ manqué.ogg`

And then:

```
$ ogginfo 01\ -\ Je\ t\'ai\ manqué.ogg

Processing file "01 - Je t'ai manqué.ogg"...

New logical stream (#1, serial: 2a848e12): type vorbis
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
...[snip]...
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
WARNING: Could not decode Vorbis header packet 2 - invalid Vorbis stream (1)
Vorbis stream 1:
	Total data length: 0 bytes
	Playback length: 0m:00.000s
	Average bitrate: -nan kb/s
Logical stream 1 ended
```

Not all files are causing this issues, but I have hundreds of examples. I was assigning genre tags to a bunch of files in my library, and a lot of them have been corrupted :crying_cat_face:

**Comment by nguillaumin** [comment] 2018-03-25 00:50
Attaching 2 files (before corruption) that exhibit the issues. Attempting to tag them corrupts them: [files.zip](https://github.com/jangler/taffy/files/1844917/files.zip)

**Comment by jangler** [comment] 2018-03-25 02:22
Ouch, that's rough. I opened an issue with taglib-ruby: https://github.com/robinst/taglib-ruby/issues/82

Until the issue is fixed upstream, maybe taffy should just refuse to save Ogg Vorbis files.

**Comment by jangler** [comment] 2018-03-25 03:01
Updated the gem and AUR package as well.

**Comment by nguillaumin** [comment] 2018-03-25 16:56
Thanks, EasyTag is suffering from a similar issue (why I switched to Taffy in the first place!) and [we have suggested just that about 1y ago](https://bugzilla.gnome.org/show_bug.cgi?id=776110#c14) but it's still corrupting Ogg files...

**Comment by jangler** [comment] 2018-03-25 17:05
A glance at that thread makes me nervous that some Opus files might also be affected, since they also use the Ogg container format. I tested on the Opus files in my library and some more converted using ffmpeg and didn't encounter any issue though, so I'm not going to add any premature restrictions on saving that format.

**Comment by jangler** [comment] 2018-03-25 17:16
This bug per se is now fixed, so I'm going to close it. I opened a separate issue to address the resulting limitation.

**Closed as completed by jangler** 2018-03-25 17:16 UTC
Labels: bug, taglib
